# Dependencies
plugins:
  - jekyll-gist
  - jekyll-paginate

# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Aaron Dou
tagline:          'Tech Blog'
description:      'Research scientist in Facebook. Interested in building secure and efficient systems and networks.'
url:              http://aarondou.github.io
baseurl:          /

author:
  name:           'Aaron Dou'
  url:            http://aarondou.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:	        
  repo:           https://github.com/poole/hyde
